name: CI_tests

on: [pull_request, push]

jobs:
  run_tests:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v1
    - name: Run tests
      run: |
        curl https://images.aarno-labs.com/amp/chx86_analyze-0.6.0_20220208-linux -o chb/bin/binaries/linux/chx86_analyze
        chmod +x chb/bin/binaries/linux/chx86_analyze
        PYTHONPATH=$PWD chb/cmdline/chkx test runall

